### ISSUE TITLE
v2.0.10 contains breaking changes 

### ISSUE THREAD

**Issue by christophe-g** [screendriver/verify-github-webhook-secret#349]
It seems version 2.0.10 breaks semantic versionning, at least in my case.

I have `^2.0.6` in a package.json that deploys to firebase-functions. 

This makes the `2.0.10` version to install on the cloud function servers, as per semantic versionning convention, which breaks the deployment of cloud functions with the following error stack: 

```
functions: updating Node.js 18 (1st Gen) function hash-emailHash(us-central1)...
Function failed on loading user code. This is likely due to a bug in the user code. Error message: Provided module can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error [ERR_REQUIRE_ESM]: require() of ES Module /workspace/node_modules/verify-github-webhook-secret/target/src/index.js from /workspace/api/controllers/webhooks/github.js not supported.
Instead change the require of index.js in /workspace/api/controllers/webhooks/github.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/workspace/api/controllers/webhooks/github.js:18:22)
    at Object.<anonymous> (/workspace/api/controllers/webhooks/index.js:5:23)
    at Object.<anonymous> (/workspace/api/controllers/index.js:13:25)
    at Object.<anonymous> (/workspace/api/routes.js:8:12)
    at Object.<anonymous> (/workspace/api/api.js:14:16)
    at Object.<anonymous> (/workspace/index.js:22:15)
    at getUserFunction (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/loader.js:96:30)
    at async main (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/main.js:35:32)
Could not load the function, shutting down.. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.

Functions deploy had errors with the following functions:
	hash-emailHash(us-central1)
i  functions: cleaning up build files...

Error: There was an error deploying functions

``` 

Quick workaround: define the exact version to be deployed on the server, hence avoiding 2.0.10.

**Comment by christophe-g** [comment]
Thanks a lot 2.0.11 works fine. Did not test 3.0.2.
